config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :questions
  root to: 'login#home', as: 'root'

  get '/home' => 'login#home', :as => :home
  get '/login/github', to: redirect('auth/github'), as: :github_login
  match '/auth/github/callback', to: 'login#github', as: :github_callback, via: [:get, :post]
  get '/logout' => 'login#logout', :as => :logout
  get '/user/profile', to: 'questions#index', as: :user_profile
  get '/repo', to: 'repo#new', as: 'repo'
  get '/sync', to: 'repo#sync', as: 'sync'
  post 'questions/search', to: 'questions#search', as: 'search_questions'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/commit.rb
class Commit < ApplicationRecord
end

app/models/question.rb
# questions model
class Question < ApplicationRecord
	# empty model but this should be updated in the future to indicate
	# the relationship between questions and repo
end

app/models/user.rb
# model for user
class User < ApplicationRecord
  # Add more Authentication Providers here
  # It is unlikely that this app need other providers
  enum provider: {github: 1}, _prefix: :provider

  # Each (uid, provider) pair should be unique
  validates :uid, uniqueness: { scope: :provider }

  def self.find_github_user(uid)
    User.find_by(
      provider: User.providers[:github],
      uid: uid
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticated

  private

  def authenticated
    @authenticated = !session[:current_user_id].nil?
  end
end

app/controllers/content_controller.rb
require 'octokit'

class ContentController < ApplicationController
  before_action :require_login!

  def require_login!
    @current_user = User.find(session[:current_user_id]) and return \
        if session[:current_user_id].present?

    session[:destination_after_login] = request.env['REQUEST_URI']
    redirect_to login_url
  end

  def new
    @client = Octokit::Client.new(:access_token => User.find(session[:current_user_id]).token)
    @user = @client.user
    @user.login
    @repos = @client.repos({}, query: {type: 'all', sort: 'full_name'})
  end
end

app/controllers/login_controller.rb
# login controller
class LoginController < ApplicationController
  before_action :already_logged_in, except: [:logout]

  def github
    create_session(:create_github_user)
  end

  def home
    if session[:current_user_id].present?
      redirect_to user_profile_path
    end
  end

  def logout
    session[:current_user_id] = nil
    redirect_to home_path, notice: 'You have successfully logged out.'
  end

  private

  # All methods below could be simplified if no other provider will be added

  def create_session(create_if_not_exists)
    user_info = request.env['omniauth.auth']
    user = find_or_create_user(user_info, create_if_not_exists)
    session[:current_user_id] = user.id
    destination_url = session[:destination_after_login] || repo_path
    session[:destination_after_login] = nil
    redirect_to destination_url
  end

  def find_or_create_user(user_info, create_if_not_exists)
    provider_sym = user_info['provider'].to_sym
    user = User.find_by(
      provider: User.providers[provider_sym],
      uid: user_info['uid']
    )
    return user unless user.nil?

    send(create_if_not_exists, user_info)
  end

  def create_github_user(user_info)
    User.create(
      uid: user_info['uid'],
      provider: User.providers[:github],
      email: user_info['info']['email'],
      token: user_info['credentials']['token']
    )
  end

  def already_logged_in
    redirect_to user_profile_path, notice: 'You are already logged in. Logout to switch accounts.'\
        if session[:current_user_id].present?
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	# Display all questions pulled from the synced repo
	def index
		@questions = find_user_repo
	end

	def search
		@questions = find_user_repo
		@search_terms = params[:search]
		@questions = @questions.where("title LIKE :search_terms OR descriptivetitle LIKE :search_terms", search_terms: Question.sanitize_sql_like(params[:search]) + "%")
		respond_to do |format|
			format.html { render partial: 'search_questions' }
		end
	end

	private

	def find_user_repo
		if session[:current_user_id].present? and session[:selected_repo].present?
			current_user = User.find(session[:current_user_id])
			if current_user != nil and current_user.repo == session[:selected_repo]
				questions = Question.where(repo: session[:selected_repo])
			end
		else
			questions = Question.where(repo: "0")
		end
		questions
	end
end

app/controllers/repo_controller.rb
# controller to get a list of repos and questions from repo
require 'octokit'
require 'json'
require "base64"

class RepoController < ApplicationController
  # All method require authenticated user
  before_action :require_login!

  def require_login!
    @current_user = User.find(session[:current_user_id]) and return \
        if session[:current_user_id].present?

    # Return to the same page after login
    session[:destination_after_login] = request.env['REQUEST_URI']
    redirect_to login_url
  end

  # Method to get list of repos given a user
  def new
    # Authenticate the user via Octokit
    @client = Octokit::Client.new(:access_token => User.find(session[:current_user_id]).token)
    @user = @client.user
    @user.login
    # Get the list of private repos
    @repos = @client.repos({}, query: {type: 'private', sort: 'full_name', per_page: 100})
  end

  # Method to synchronize or get questions from a selected repo
  def sync
    # Get the repo from the selected dropdown in the views
    @repo = params[:repo_id]

    # Authenticate the user via Octokit
    @client = Octokit::Client.new(:access_token => User.find(session[:current_user_id]).token)
    @user = @client.user
    @user.login

    # Initial path which is defined by PrairieLearn documentations
    path = 'questions'

    # Check cache
    checkCommit(@client, @repo, path)
    session[:selected_repo] = @repo
    User.find(session[:current_user_id]).update(repo: @repo)
    redirect_to root_path
  end

  # Method to check if a repo has been pulled
  def checkCommit(client, repo, path)
    root = client.contents(repo, path: "/")

    # For each directory, check if the commit ID is different
    root.each do |dir|
      if dir.name == path
        repo_commit = Commit.find_by repo: repo
        # If the commit is not found, pull and create commit
        if repo_commit != nil
          if repo_commit.sha == dir.sha
            # If the commit is identical, use the available cached file
            return
          else
            # If the commit is different, destroy record
            Question.destroy_by(repo: repo)
            repo_commit.update(sha: dir.sha)
          end
        else
          Commit.create(sha: dir.sha, repo: repo)
        end
      end
    end
    # Pulling questions via helper method
    addQuestions(client, repo, path)
  end

  # Helper method to get all questions
  def addQuestions(client, repo, path)
    contents = client.contents(repo, path: path)
    contents.each do |file|
      # If .JSON file is found, keep the path
      if file.name == "info.json"
        question_name = file.path.partition('/')[2].rpartition('/')[0]
        
        path_str = path+"/info.json"

        contentsJsonInfobase64 = client.contents(repo, path: path_str)
        
        descriptive_title = JSON.parse(Base64.decode64(contentsJsonInfobase64[:content]))["title"]

        Question.create(title: question_name, descriptivetitle: descriptive_title, repo: repo)
      end
      # Recursively call the helper method if current file is a folder
      if file.type == 'dir'
        new_path = path + '/' + file.name
        addQuestions(client, repo, new_path)
      end
    end
  end
end

app/controllers/session_controller.rb
# session controller
class SessionController < ApplicationController
  before_action :require_login!

  private

  def require_login!
    @current_user = User.find(session[:current_user_id]) and return \
        if session[:current_user_id].present?

    session[:destination_after_login] = request.env['REQUEST_URI']
    redirect_to login_url
  end
end

app/controllers/user_controller.rb
# This file could be deleted
# user controller
class UserController < SessionController
  def profile
    #@user = User.find(session[:current_user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/homepage.html.erb
<!DOCTYPE html>
<html>
  <head>
  </head>

  <body>
    <p>PrairieLearn</p>
    <form>
        <label>Assessment name:</label><br>
        <input type="text"><br><br>

        <label>Type:</label><br>
        <select>
          <option>Exam</option>
          <option>Quiz</option>
          <option>Homework</option>
          <option>Vitamin</option>
          <option>Worksheet</option>
        </select><br><br>

        <label>Credit:</label><br>
        <input type="text" value="100"><br><br>

        <label>Allow access to:</label><br>
        <select>
        	<option>David Oh</option>
          <option>Faiz Shamji</option>
          <option>Timothy Vincent</option>
          <option>Haolin Zhu</option>
          <option>Sanwu Luo</option>
        </select><br>
        <label>Start date:</label><br>
        <input type="date" value="2021-02-23" min="2021-02-23" max="2021-12-31"><br>
        <label>End date:</label><br>
        <input type="date" value="2021-02-26" min="2021-02-23" max="2021-12-31"><br>
        <input type="button" value="+"><br><br>

        <input type="button" value="Submit"<br>
    </form>

  </body>
</html>

app/views/content/new.html.erb
<html>
  <body>
    <div>
      <%= 'All repos' %>
      <br>
      <p> Choose a repository to synchronize: </p>
      <form>
        <select name = 'repository'>
          <%= select_tag 'repo_id', options_for_select(repos.map {|repo| [repo.full_name, repo.full_name]}) %>
          
        </select>
      </form>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrairieLearn</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js" type="text/javascript"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js" type="text/javascript"></script>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <nav>
      <div class="nav-wrapper">
        <div id="name">PrairieLearn Assessment Configuration File Generator</div>
      </div>
    </nav>
    <div>
      <div class="container h-100">
        <div class="row align-items-center h-100">
          <div class="col-6 mx-auto">
              <div class="jumbotron">
                <blockquote class="blockquote text-center align-middle">
                  <h4>Welcome!</h4>
                  <h5>To start creating a new assessment, please login.</h5><br>
                  <%= form_tag('/auth/github', method: 'post', data: {turbo: false}) do %>
                    <button type='submit'>Login with Github</button>
                  <% end %>
                </blockquote>
              </div>
          </div>
        </div>
      </div>
    <div class="footer"></div>
  </body>
</html>

app/views/login/login.html.erb
<!DOCTYPE html>

<html>
  <body>
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <span class="d-block display-4 card-title text-center">Sign In</span>
            <div class="alert alert-primary text-center" role="<%= :alert %>">
              Select an authentication provider below to login.
            </div>
            <%= link_to "Log In", :github_login%>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/questions/_search_questions.html.erb
<div class='list-group question_title'><% @questions.each do |question| %>
    <tr>
    <p class="list-group-item draggable-question draggable-text" name=<%= question.title %> draggable="true">
        <td><%= question.descriptivetitle %></td>
        <span class="close" style="display:none">&times;</span>

        <input class="form-control col-md-1 mb-1" hidden type="text" name="assessment_credit" placeholder="0" size=1>
        <label for="form-control" class="pts-txt" style="display: none">Pts</label>
    </p>
    </tr>
    <% end %>
</div>

<script>
$(".draggable-question").css('text-align','left').draggable({
    helper: "clone",
    connectToSortable: ".mcontainer",
    revert: "invalid"
});

</script>

app/views/questions/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js" type="text/javascript"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js" type="text/javascript"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/fe1e3d4772.js" crossorigin="anonymous"></script>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
    <div id="questions page">
    <nav class="navbar navbar-expand-lg">
      <div id="name" style="font-size:23px">Create New Assessment</div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item mx-1">
            <%= link_to 'Repo', repo_path(), :class => 'btn btn-primary' %>
          </li>
          <li class="nav-item mx-1">
            <%= link_to 'Logout', logout_path(), :class => 'btn btn-primary' %>
          </li>
          <li class="nav-item mx-1">
            <button class="btn btn-primary" type="button" id="export">Export</button>
            <a id="downloadAnchorElem" style="display:none"></a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="qcol rightcol">
      <p class= "mt-3">Configurations</p>
      <form id="config">
        <div class='configs'>
          <div class="form-group w-75">
            <label class='question_title'>Assessment name:</label>
            <input class="form-control" type="text" placeholder="Enter assessment name" name="title" size=36>
          </div>
          <div class="form-row">
            <div class="col-md-5 mb-3">
              <label class='question_title'>Type:</label>
              <select class="form-control" name="type">
                <option>Exam</option>
                <option>Homework</option>
              </select>
            </div>
            <div class="col-md-5 mb-3">
              <label class='question_title'>Credit:</label>
              <input class="form-control" type="text" placeholder="Enter integer" name="credit" size=4>
            </div>
          </div>
          <div class="form-row">
            <div class="col-md-5 mb-3">
              <label class='question_title'>Number:</label>
              <input class="form-control" type="text" placeholder="Enter integer" name="number" size=4>
            </div>
            <div class="col-md-5 mb-3">
              <label class='question_title'>Set:</label>
              <input class="form-control" type="text" placeholder="Enter set name" name="set" size=4>
            </div>
          </div>
          <hr>
          <div class="access_forms">
            <div class="form-group w-50">
              <label class='question_title'>Allow access to:</label>
              <select class="form-control" name="role">
                <option>Student</option>
                <option>TA</option>
                <option>Instructor</option>
              </select>
            </div>
            <label class='question_title'>Start date:</label>
            <div class="form-row">
              <div class="col-md-5 mb-3">
                <input class="form-control" type="date" min="2021-01-01" max="2100-12-31" name="startDate">
              </div>
              <div class="col-md-5 mb-3">
                <input class="form-control" type="time" min="00:00" max="23:59" name="startTime">
              </div>
            </div>
            <label class='question_title'>End date:</label>
            <div class="form-row">
              <div class="col-md-5 mb-3">
                <input class="form-control" type="date" min="2021-03-02" max="2100-12-31" name="endDate">
              </div>
              <div class="col-md-5 mb-3">
                <input class="form-control" type="time" min="00:00" max="23:59" name="endTime">
              </div>
            </div>
            <hr>
          </div>
          <button class="btn btn-primary btn-lg" type="button" id="add_access">+</button>
          <button class="btn btn-primary btn-lg" type="button" id="delete_access">-</button>
          <script>
          $(document).ready(function(){
            // Spawns new access forms
            $('#add_access').click(function(){
              // Create clone of <div class='input-form'>
              var newel = $('.access_forms:last').clone(true);
              // Add after last <div class='input-form'>
              $(newel).insertAfter(".access_forms:last");
            });
            // Deletes previous access forms
            $('#delete_access').click(function() {
              var count = $('.access_forms').length;
              if (count > 1)  // change this to 1 if you want at least one to show
                $( ".access_forms:last" ).remove();
            });
          });
          </script>
        </div><br>
      </form>
    </div>

    <div class="qcol middlecol">
      <p class="test mt-3">Selected Questions</p>
      <%= render 'selected_questions' %>
    </div>

    <div class="qcol leftcol">
      <p class = "mt-3">Questions</p>
      
      <div class="row justify-content-center col-auto">
        <%= form_tag search_questions_path, method: :post do %>
          <%= text_field_tag :search, nil, placeholder: "Search for a question..." %>
          <%= submit_tag "Search" %>
        <% end %>
      </div>

      <div class="qcontainer">
        <%= render 'search_questions' %>
      </div>

  <script>
    $(document).on('submit', 'form', function(event) {
      event.preventDefault();
      var searchValue = $('input[name="search"]').val();
      $.ajax({
        url: $(this).attr('action'),
        type: $(this).attr('method'),
        data: { search: searchValue },
        success: function(response) {
          $('.qcontainer').html(response);
          $('.qcontainer .draggable-question').css('text-align','left').draggable({
            helper: "clone",
            connectToSortable: ".mcontainer",
            revert: "invalid"
          });
        }
      });
    });
    
    function uuidCall() {
      return new Promise(function(resolve, reject) {
        $.ajax({
          url: "https://www.uuidgenerator.net/api/version4",
          type: "GET",
          success: function(data) {
            // UUID Received!
            resolve(data)
          },
          error: function(err) {
            reject(err)
          }
        });
      });
    }

    $(document).ready(function(){
      // trigger export
      $('#export').click(function(){
        jsonData = {}
        uuidCall().then(function(data) {
          jsonData['uuid'] = data
          dateData = {} // store the date information for jsonDate
          allowAccessData = {}
          var formData = $("#config").serializeArray();
          $.each(formData, function() {
            switch (this.name) {
              case 'role':
              case 'mode':
                allowAccessData[this.name] = this.value
                break;
              case 'credit':
                allowAccessData[this.name] = new Number(this.value)
                break;
              case 'startDate':
              case 'endDate':
              case 'startTime':
              case 'endTime':
                dateData[this.name] = this.value
                break;
              default:
                jsonData[this.name] = this.value
            }
          });
          allowAccessData['startDate'] = dateData.startDate + 'T' + dateData.startTime
          allowAccessData['endDate'] = dateData.endDate + 'T' + dateData.endTime

          if (Object.keys(allowAccessData).length > 0){
            allowAccessData['mode'] = 'Public'
            if ('allowAccess' in jsonData){
              jsonData.allowAccess.push(allowAccessData)
            } else {
              jsonData.allowAccess = [allowAccessData]
            }
          }

          const midZones = document.getElementsByClassName("zone");
          if (!(midZones.length == 1 && 
              midZones[0].querySelector("#zone_title").value == "" &&
              midZones[0].querySelector("#zone_comment").value == "" &&
              midZones[0].querySelectorAll('.draggable-question[type="outer"]').length == 0)) {
            jsonData.zones = [];
            for (let i = 0; i < midZones.length; i++) {
              jsonData.zones.push({
                title: midZones[i].querySelector("#zone_title").value,
                comment: midZones[i].querySelector("#zone_comment").value,
                questions: []
              });
              const midQuestions = midZones[i].querySelectorAll('.draggable-question[type="outer"]');
              for (let j = 0; j < midQuestions.length; j++) {
                const alternatives = midQuestions[j].querySelectorAll('.draggable-question[type="inner"]');
                if (alternatives.length > 0) {
                  const pt = new Number(midQuestions[j].querySelector(".form-control").value);
                  jsonData.zones[i].questions.push({
                    numberChoose: new Number(midQuestions[j].querySelector("#numchoose").value),
                    points: pt,
                    alternatives: []
                  });
                  for (let k = 0; k < alternatives.length; k++) {
                    jsonData.zones[i].questions[j].alternatives.push({
                      id: alternatives[k].getAttribute('name'),
                      points: pt
                    });
                  }
                } else {
                  jsonData.zones[i].questions.push({
                    id: midQuestions[j].getAttribute('name'),
                    points: new Number(midQuestions[j].querySelector(".form-control").value)
                  });
                }
              }
            }
          }              

          var dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(jsonData, null, '\t'));
          var dlAnchorElem = document.getElementById('downloadAnchorElem');
          dlAnchorElem.setAttribute("href",     dataStr     );
          dlAnchorElem.setAttribute("download", "infoAssessment.json");
          dlAnchorElem.click();
        }).catch(function(err){
          console.log(err)
        })
      });
    });

    window.onbeforeunload = function() {
      return "Are you sure?";
    };

    window.onkeydown = function(event) {
      if (event.keyCode === 116) {
        window.location.reload();
      }
    };
    </script>

  </body>
</html>

app/views/repo/new.html.erb
<html>
<head>
  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
  <body>
    <nav>
      <div class="nav-wrapper">
        <div id="name">PrairieLearn Assessment Configuration File Generator</div>
      </div>
    </nav>
    <div class="container h-100">
        <div class="row align-items-center h-100">
          <div class="col-6 mx-auto">
              <div class="jumbotron">
                <blockquote class="blockquote text-center align-middle">
                  <h4>Choose a repository to synchronize:</h4><br>
                  <%= form_with url: "/sync", method: :get do |form| %>
                    <%= form.select :repo_id, @repos.map { |repo| [repo.full_name] }, {class: "form-control"} %>
                    <%= form.submit "Synchronize", :class => 'btn btn-primary' %>
                  <% end %>
                </blockquote>
              </div>
          </div>
        </div>
      </div>
    <div class="footer"></div>
  </body>
</html>